// THIS FILE IS AUTO-GENERATED BY update_assets.sh!

use crate::assets::add_asset;

pub fn load_dynamic_assets() {


add_asset(
        &["/static/js/0.1745f3d8.chunk.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/js/0.1745f3d8.chunk.js.gz").to_vec(),
    );
add_asset(
        &["/static/js/3.d0df9ade.chunk.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/js/3.d0df9ade.chunk.js.gz").to_vec(),
    );
add_asset(
        &["/static/js/4.23788c49.chunk.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/js/4.23788c49.chunk.js.gz").to_vec(),
    );
add_asset(
        &["/static/js/5.c4d9bc96.chunk.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/js/5.c4d9bc96.chunk.js.gz").to_vec(),
    );
add_asset(
        &["/static/js/6.e82e6c95.chunk.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/js/6.e82e6c95.chunk.js.gz").to_vec(),
    );
add_asset(
        &["/static/js/7.068aa5c1.chunk.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/js/7.068aa5c1.chunk.js.gz").to_vec(),
    );
add_asset(
        &["/static/js/main.92d6ff8e.chunk.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/js/main.92d6ff8e.chunk.js.gz").to_vec(),
    );
add_asset(
        &["/static/js/runtime-main.620106c4.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/js/runtime-main.620106c4.js.gz").to_vec(),
    );
add_asset(
        &["/static/css/3.fc8ef173.chunk.css"],
        vec![
            ("Content-Type".to_string(), "text/css".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/css/3.fc8ef173.chunk.css.gz").to_vec(),
    );
add_asset(
        &["/static/css/main.2b69f7b7.chunk.css"],
        vec![
            ("Content-Type".to_string(), "text/css".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/css/main.2b69f7b7.chunk.css.gz").to_vec(),
    );
    add_asset(
        &["/bonds/bond-info.png"],
        vec![
            ("Content-Type".to_string(), "image/png".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/bonds/bond-info.png").to_vec(),
    );
    add_asset(
        &["/bonds/egg-nft.png"],
        vec![
            ("Content-Type".to_string(), "image/png".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/bonds/egg-nft.png").to_vec(),
    );
add_asset(
    &["/ic.svg"],
    vec![
        ("Content-Type".to_string(), "image/svg+xml".to_string()),
        ("Cache-Control".to_string(), "public".to_string()),
    ],
    include_bytes!("../../build/ic.svg").to_vec(),
);

}
