// THIS FILE IS AUTO-GENERATED BY update_assets.sh!

use crate::assets::add_asset;

pub fn load_dynamic_assets() {


add_asset(
        &["/static/js/2.3a3f71f3.chunk.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/js/2.3a3f71f3.chunk.js.gz").to_vec(),
    );
add_asset(
        &["/static/js/3.4caed6e5.chunk.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/js/3.4caed6e5.chunk.js.gz").to_vec(),
    );
add_asset(
        &["/static/js/4.77cfc765.chunk.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/js/4.77cfc765.chunk.js.gz").to_vec(),
    );
add_asset(
        &["/static/js/5.b698af77.chunk.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/js/5.b698af77.chunk.js.gz").to_vec(),
    );
add_asset(
        &["/static/js/6.05012627.chunk.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/js/6.05012627.chunk.js.gz").to_vec(),
    );
add_asset(
        &["/static/js/main.a24633a9.chunk.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/js/main.a24633a9.chunk.js.gz").to_vec(),
    );
add_asset(
        &["/static/js/runtime-main.8e365caf.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/js/runtime-main.8e365caf.js.gz").to_vec(),
    );
add_asset(
        &["/static/css/2.fc8ef173.chunk.css"],
        vec![
            ("Content-Type".to_string(), "text/css".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/css/2.fc8ef173.chunk.css.gz").to_vec(),
    );
add_asset(
        &["/static/css/main.2b69f7b7.chunk.css"],
        vec![
            ("Content-Type".to_string(), "text/css".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/static/css/main.2b69f7b7.chunk.css.gz").to_vec(),
    );
    add_asset(
        &["/bonds/bond-info.png"],
        vec![
            ("Content-Type".to_string(), "image/png".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/bonds/bond-info.png").to_vec(),
    );
    add_asset(
        &["/bonds/egg-nft.png"],
        vec![
            ("Content-Type".to_string(), "image/png".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/bonds/egg-nft.png").to_vec(),
    );
add_asset(
    &["/ic.svg"],
    vec![
        ("Content-Type".to_string(), "image/svg+xml".to_string()),
        ("Cache-Control".to_string(), "public".to_string()),
    ],
    include_bytes!("../../build/ic.svg").to_vec(),
);

}
