[package]
name = "themis"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
base64 = "0.13.0"
candid = "0.7.8"
ic-cdk = { git = "https://github.com/dfinity/cdk-rs", rev = "a080645844d2c761639707a58e51d400543eabce" }
ic-cdk-macros = { git = "https://github.com/dfinity/cdk-rs", rev = "a080645844d2c761639707a58e51d400543eabce" }
ic-certified-map = { git = "https://github.com/dfinity/cdk-rs", rev = "a080645844d2c761639707a58e51d400543eabce" }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.6"
serde_cbor = "0.11"
serde_json = "1.0"
sha2 = "0.9.1"
